{{- if .Values.applicationSet.enabled }}
apiVersion: v1
kind: Service
metadata:
{{- if .Values.applicationSet.service.annotations }}
  annotations:
  {{- range $key, $value := .Values.applicationSet.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  name: {{ template "argo-cd.applicationSet.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "argo-cd.labels" (dict "context" . "component" .Values.applicationSet.name "name" .Values.applicationSet.name) | nindent 4 }}
{{- with .Values.applicationSet.service.labels }}
{{- toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.applicationSet.service.type }}
{{- if .Values.applicationSet.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.applicationSet.service.ipFamilyPolicy }}
{{- end }}
{{- if .Values.applicationSet.service.ipFamilies }}
  ipFamilies: {{ .Values.applicationSet.service.ipFamilies | toYaml | nindent 2 }}
{{- end }}
  ports:
  - name: {{ .Values.applicationSet.service.portName }}
    port: {{ .Values.applicationSet.service.port }}
    targetPort: webhook
  selector:
    {{- include "argo-cd.selectorLabels" (dict "context" . "name" .Values.applicationSet.name) | nindent 4 }}
{{- end }}
